"""PostgreSQL C extension crypto detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PG_C_EXT_RULES = [
    {
        "id": "pg_evp_encrypt",
        "name": "OpenSSL EVP_EncryptInit in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(EVP_EncryptInit_ex|EVP_DecryptInit_ex)",
        },
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "Open EVP Encryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "modern-api"],
        },
        "replacement": "Ensure using EVP_aes_256_gcm() for authenticated encryption",
        "priority": "P3-Low",
        "effort": "Low",
    },
    {
        "id": "pg_rsa_generate",
        "name": "RSA Key Generation in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(RSA_generate_key_ex|RSA_public_encrypt|RSA_private_decrypt|RSA_sign|RSA_verify)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "RSA in PG Extension",
            "primitive": "key-encapsulation",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "shor-breakable"],
        },
        "replacement": "Replace RSA with ML-KEM-1024 (FIPS 203) for key exchange, ML-DSA-65 (FIPS 204) for signatures",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pg_ecdh_keygen",
        "name": "ECDH Key Generation in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(EC_KEY_new_by_curve_name|ECDH_compute_key|EC_KEY_generate_key)",
        },
        "algorithm": {
            "algorithmFamily": "ECDH",
            "algorithmName": "ECDH in PG Extension",
            "primitive": "key-exchange",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "shor-breakable"],
        },
        "replacement": "Replace ECDH with ML-KEM-768 + X25519 hybrid",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pg_ssl_ctx",
        "name": "OpenSSL SSL_CTX in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(SSL_CTX_new|TLS_server_method|TLS_client_method)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "OpenSSL TLS in PG Extension",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["tls-enabled"],
        },
        "replacement": "Ensure using TLS 1.3 with PQC cipher suites",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "pg_ecdsa_sign",
        "name": "ECDSA Signing in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(ECDSA_sign|ECDSA_verify|ECDSA_SIG_new)",
        },
        "algorithm": {
            "algorithmFamily": "ECDSA",
            "algorithmName": "ECDSA in PG Extension",
            "primitive": "digital-signature",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "signature-broken"],
        },
        "replacement": "Replace ECDSA with ML-DSA-65 (FIPS 204) or SPHINCS+ (FIPS 205)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pg_hmac_sha1",
        "name": "HMAC-SHA1 in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(HMAC\(.*EVP_sha1\(\))",
        },
        "algorithm": {
            "algorithmFamily": "HMAC",
            "algorithmName": "HMAC-SHA1 in PG Extension",
            "primitive": "mac",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-broken", "quantum-vulnerable"],
        },
        "replacement": "Replace HMAC-SHA1 with HMAC-SHA256",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "pg_md5_direct",
        "name": "Direct MD5 Usage in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(MD5\(|EVP_md5\(\)|EVP_get_digestbyname\(['\"]md5['\"])\)",
        },
        "algorithm": {
            "algorithmFamily": "MD5",
            "algorithmName": "MD5 in PG Extension",
            "primitive": "hash",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-vulnerable", "quantum-vulnerable"],
        },
        "replacement": "Replace MD5 with SHA-256 or SHA-3-256",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "pg_pkey_derive",
        "name": "EVP_PKEY Derive in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(EVP_PKEY_derive|EVP_PKEY_keygen|EVP_PKEY_CTX_new_id)",
        },
        "algorithm": {
            "algorithmFamily": "ECDH",
            "algorithmName": "EVP_PKEY Key Derivation",
            "primitive": "key-exchange",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "depends-on-algorithm"],
        },
        "replacement": "Ensure using PQC algorithm (ML-KEM) with EVP_PKEY API",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "pg_digest_direct",
        "name": "Direct SHA-256 Digest in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(SHA256\(|EVP_sha256\(\)|EVP_DigestInit_ex.*sha256)",
        },
        "algorithm": {
            "algorithmFamily": "SHA-2",
            "algorithmName": "SHA-256 in PG Extension",
            "primitive": "hash",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["collision-resistant", "quantum-weakened-but-safe"],
        },
        "replacement": "None needed - SHA-256 is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "pg_aes_gcm",
        "name": "AES-GCM in PG Extension",
        "category": "pg_c_ext",
        "file_patterns": ["*.c", "*.h"],
        "patterns": {
            "c": r"\b(EVP_aes_256_gcm|EVP_aes_128_gcm)",
        },
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "AES-GCM in PG Extension",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "authenticated", "modern"],
        },
        "replacement": "None needed - AES-GCM is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
]
