"""PostgreSQL certificate management detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PG_CERT_RULES = [
    {
        "id": "pg_server_crt",
        "name": "PostgreSQL Server Certificate",
        "category": "pg_cert",
        "file_patterns": ["*.crt", "*.pem", "*.conf"],
        "patterns": {
            "config": r"\b(server\.crt|server\.pem|ssl_cert_file\s*=\s*['\"]([^'\"]*server\.(crt|pem))['\"])",
            "c": r"\b(server\.crt|server\.pem)",
            "sql": r"\b(server\.crt|server\.pem)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "PostgreSQL Server Certificate",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "server-identity"],
        },
        "replacement": "Regenerate server certificate with ML-KEM or ECDSA P-384",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "pg_server_key",
        "name": "PostgreSQL Server Private Key",
        "category": "pg_cert",
        "file_patterns": ["*.key", "*.pem", "*.conf"],
        "patterns": {
            "config": r"\b(server\.key|ssl_key_file\s*=\s*['\"]([^'\"]*server\.key)['\"])",
            "c": r"\b(server\.key)",
            "sql": r"\b(server\.key)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "PostgreSQL Server Key",
            "primitive": "certificate",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "private-key-exposure"],
        },
        "replacement": "Regenerate server key with RSA-4096+ or ECDSA P-384+ (quantum-resistant minimum)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pg_root_ca",
        "name": "PostgreSQL Root CA Certificate",
        "category": "pg_cert",
        "file_patterns": ["*.crt", "*.pem", "*.conf"],
        "patterns": {
            "config": r"\b(root\.crt|ca\.crt|ssl_ca_file\s*=\s*['\"]([^'\"]*\.(crt|pem))['\"])",
            "c": r"\b(root\.crt|ca\.crt)",
            "sql": r"\b(root\.crt|ca\.crt)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "PostgreSQL Root CA",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "ca-signing-key"],
        },
        "replacement": "Regenerate CA with ML-DSA-65 (FIPS 204) or ECDSA P-384",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "pg_client_cert",
        "name": "PostgreSQL Client Certificate",
        "category": "pg_cert",
        "file_patterns": ["*.crt", "*.pem", "*.conf"],
        "patterns": {
            "config": r"\b(client\.crt|sslcert\s*=\s*['\"]([^'\"]*client\.crt)['\"])",
            "c": r"\b(client\.crt)",
            "sql": r"\b(client\.crt)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "PostgreSQL Client Certificate",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "client-auth"],
        },
        "replacement": "Regenerate client certificate with ML-DSA-65 (FIPS 204) or ECDSA P-384",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "pg_client_key",
        "name": "PostgreSQL Client Private Key",
        "category": "pg_cert",
        "file_patterns": ["*.key", "*.pem", "*.conf"],
        "patterns": {
            "config": r"\b(client\.key|sslkey\s*=\s*['\"]([^'\"]*client\.key)['\"])",
            "c": r"\b(client\.key)",
            "sql": r"\b(client\.key)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "PostgreSQL Client Key",
            "primitive": "certificate",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "private-key-exposure"],
        },
        "replacement": "Regenerate client key with RSA-4096+ or ECDSA P-384+ (quantum-resistant minimum)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pg_crl",
        "name": "PostgreSQL Certificate Revocation List",
        "category": "pg_cert",
        "file_patterns": ["*.crl", "*.pem", "*.conf"],
        "patterns": {
            "config": r"\b(root\.crl|ssl_crl_file\s*=\s*['\"]([^'\"]*\.crl)['\"])",
            "c": r"\b(root\.crl)",
            "sql": r"\b(root\.crl)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "PostgreSQL CRL",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["crl-configured"],
        },
        "replacement": "Ensure CRL is signed with SHA-256+ algorithm",
        "priority": "P3-Low",
        "effort": "Low",
    },
]
