"""PostgreSQL connection string pattern detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PG_CONN_STRING_RULES = [
    {
        "id": "conn_sslmode_allow",
        "name": "Connection String sslmode=allow",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslmode\s*=\s*['\"]?allow['\"]?|postgresql://.*sslmode=allow)",
            "java": r"\b(sslmode\s*=\s*['\"]?allow['\"]?|jdbc:postgresql://.*sslmode=allow)",
            "javascript": r"\b(sslmode:\s*['\"]allow['\"]|sslmode=allow)",
            "go": r"\b(sslmode\s*=\s*['\"]?allow['\"]?|sslmode=allow)",
            "c": r"\b(sslmode\s*=\s*['\"]?allow['\"]?|sslmode=allow)",
            "config": r"\b(sslmode\s*=\s*['\"]?allow['\"]?|sslmode=allow)",
            "sql": r"\b(sslmode\s*=\s*['\"]?allow['\"]?|sslmode=allow)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection sslmode=allow",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["ssl-optional", "downgrade-risk", "no-encryption-guarantee"],
        },
        "replacement": "Use sslmode=verify-full or sslmode=require",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "conn_sslmode_prefer",
        "name": "Connection String sslmode=prefer",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslmode\s*=\s*['\"]?prefer['\"]?|postgresql://.*sslmode=prefer)",
            "java": r"\b(sslmode\s*=\s*['\"]?prefer['\"]?|jdbc:postgresql://.*sslmode=prefer)",
            "javascript": r"\b(sslmode:\s*['\"]prefer['\"]|sslmode=prefer)",
            "go": r"\b(sslmode\s*=\s*['\"]?prefer['\"]?|sslmode=prefer)",
            "c": r"\b(sslmode\s*=\s*['\"]?prefer['\"]?|sslmode=prefer)",
            "config": r"\b(sslmode\s*=\s*['\"]?prefer['\"]?|sslmode=prefer)",
            "sql": r"\b(sslmode\s*=\s*['\"]?prefer['\"]?|sslmode=prefer)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection sslmode=prefer",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["ssl-optional", "downgrade-risk", "mitm-possible"],
        },
        "replacement": "Use sslmode=verify-full",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "conn_sslmode_require",
        "name": "Connection String sslmode=require",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslmode\s*=\s*['\"]?require['\"]?|postgresql://.*sslmode=require)",
            "java": r"\b(sslmode\s*=\s*['\"]?require['\"]?|jdbc:postgresql://.*sslmode=require)",
            "javascript": r"\b(sslmode:\s*['\"]require['\"]|sslmode=require)",
            "go": r"\b(sslmode\s*=\s*['\"]?require['\"]?|sslmode=require)",
            "c": r"\b(sslmode\s*=\s*['\"]?require['\"]?|sslmode=require)",
            "config": r"\b(sslmode\s*=\s*['\"]?require['\"]?|sslmode=require)",
            "sql": r"\b(sslmode\s*=\s*['\"]?require['\"]?|sslmode=require)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection sslmode=require",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["ssl-required", "no-cert-verification", "mitm-possible"],
        },
        "replacement": "Use sslmode=verify-full",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "conn_sslmode_verify_full",
        "name": "Connection String sslmode=verify-full",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslmode\s*=\s*['\"]?verify-full['\"]?|postgresql://.*sslmode=verify-full)",
            "java": r"\b(sslmode\s*=\s*['\"]?verify-full['\"]?|jdbc:postgresql://.*sslmode=verify-full)",
            "javascript": r"\b(sslmode:\s*['\"]verify-full['\"]|sslmode=verify-full)",
            "go": r"\b(sslmode\s*=\s*['\"]?verify-full['\"]?|sslmode=verify-full)",
            "c": r"\b(sslmode\s*=\s*['\"]?verify-full['\"]?|sslmode=verify-full)",
            "config": r"\b(sslmode\s*=\s*['\"]?verify-full['\"]?|sslmode=verify-full)",
            "sql": r"\b(sslmode\s*=\s*['\"]?verify-full['\"]?|sslmode=verify-full)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection sslmode=verify-full",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["ssl-verified", "cert-validated", "mitm-prevented"],
        },
        "replacement": "Already using recommended sslmode",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "conn_sslmode_disable",
        "name": "Connection String sslmode=disable",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslmode\s*=\s*['\"]?disable['\"]?|postgresql://.*sslmode=disable)",
            "java": r"\b(sslmode\s*=\s*['\"]?disable['\"]?|jdbc:postgresql://.*sslmode=disable)",
            "javascript": r"\b(sslmode:\s*['\"]disable['\"]|sslmode=disable)",
            "go": r"\b(sslmode\s*=\s*['\"]?disable['\"]?|sslmode=disable)",
            "c": r"\b(sslmode\s*=\s*['\"]?disable['\"]?|sslmode=disable)",
            "config": r"\b(sslmode\s*=\s*['\"]?disable['\"]?|sslmode=disable)",
            "sql": r"\b(sslmode\s*=\s*['\"]?disable['\"]?|sslmode=disable)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection sslmode=disable",
            "primitive": "certificate",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["no-ssl", "plaintext-transmission", "critical-risk"],
        },
        "replacement": "Enable SSL: use sslmode=verify-full",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "conn_sslcert",
        "name": "Connection String sslcert Parameter",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslcert\s*=\s*['\"](.+?)['\"]|postgresql://.*sslcert=)",
            "java": r"\b(sslcert\s*=\s*['\"](.+?)['\"]|jdbc:postgresql://.*sslcert=)",
            "javascript": r"\b(sslcert:\s*['\"](.+?)['\"]|sslcert=)",
            "go": r"\b(sslcert\s*=\s*['\"](.+?)['\"]|sslcert=)",
            "c": r"\b(sslcert\s*=\s*['\"](.+?)['\"]|sslcert=)",
            "config": r"\b(sslcert\s*=\s*['\"](.+?)['\"]|sslcert=)",
            "sql": r"\b(sslcert\s*=\s*['\"](.+?)['\"]|sslcert=)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection Client Certificate",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "depends-on-cert-key"],
        },
        "replacement": "Ensure client certificate uses PQC keys (ML-DSA or ECDSA P-384)",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "conn_sslrootcert",
        "name": "Connection String sslrootcert Parameter",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslrootcert\s*=\s*['\"](.+?)['\"]|postgresql://.*sslrootcert=)",
            "java": r"\b(sslrootcert\s*=\s*['\"](.+?)['\"]|jdbc:postgresql://.*sslrootcert=)",
            "javascript": r"\b(sslrootcert:\s*['\"](.+?)['\"]|sslrootcert=)",
            "go": r"\b(sslrootcert\s*=\s*['\"](.+?)['\"]|sslrootcert=)",
            "c": r"\b(sslrootcert\s*=\s*['\"](.+?)['\"]|sslrootcert=)",
            "config": r"\b(sslrootcert\s*=\s*['\"](.+?)['\"]|sslrootcert=)",
            "sql": r"\b(sslrootcert\s*=\s*['\"](.+?)['\"]|sslrootcert=)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection Root CA Certificate",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["ca-validated", "cert-pinning"],
        },
        "replacement": "Ensure CA uses SHA-256+ signing algorithm",
        "priority": "P3-Low",
        "effort": "Low",
    },
    {
        "id": "conn_sslkey",
        "name": "Connection String sslkey Parameter",
        "category": "pg_conn",
        "file_patterns": ["*.py", "*.java", "*.js", "*.ts", "*.go", "*.rb", "*.php", "*.rs"],
        "patterns": {
            "python": r"\b(sslkey\s*=\s*['\"](.+?)['\"]|postgresql://.*sslkey=)",
            "java": r"\b(sslkey\s*=\s*['\"](.+?)['\"]|jdbc:postgresql://.*sslkey=)",
            "javascript": r"\b(sslkey:\s*['\"](.+?)['\"]|sslkey=)",
            "go": r"\b(sslkey\s*=\s*['\"](.+?)['\"]|sslkey=)",
            "c": r"\b(sslkey\s*=\s*['\"](.+?)['\"]|sslkey=)",
            "config": r"\b(sslkey\s*=\s*['\"](.+?)['\"]|sslkey=)",
            "sql": r"\b(sslkey\s*=\s*['\"](.+?)['\"]|sslkey=)",
        },
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Connection Client Private Key",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "private-key"],
        },
        "replacement": "Ensure private key uses RSA-4096+ or ECDSA P-384+ (quantum-resistant minimum)",
        "priority": "P1-High",
        "effort": "High",
    },
]
