"""PostgreSQL pg_hba.conf authentication method detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PG_HBA_RULES = [
    {
        "id": "pg_hba_md5",
        "name": "pg_hba.conf MD5 Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(host|local)\s+.+\s+md5\s*$",
        },
        "check_func": "check_hba_md5",
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "MD5 Password Auth",
            "primitive": "kdf",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["quantum-vulnerable", "collision-broken", "deprecated"],
        },
        "replacement": "Replace md5 with scram-sha-256 in pg_hba.conf",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "pg_hba_password",
        "name": "pg_hba.conf Password (Plaintext) Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(host|local)\s+.+\s+password\s*$",
        },
        "check_func": "check_hba_password",
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "Plaintext Password Auth",
            "primitive": "kdf",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["plaintext-transmission", "no-hashing", "critical-risk"],
        },
        "replacement": "Replace password with scram-sha-256 in pg_hba.conf",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "pg_hba_scram_sha256",
        "name": "pg_hba.conf SCRAM-SHA-256 Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(host|local)\s+.+\s+scram-sha-256\s*$",
        },
        "check_func": "check_hba_scram",
        "algorithm": {
            "algorithmFamily": "SASL",
            "algorithmName": "SCRAM-SHA-256 Auth",
            "primitive": "mac",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-weakened-but-safe", "salted", "modern-auth"],
        },
        "replacement": "None needed - SCRAM-SHA-256 is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "pg_hba_cert",
        "name": "pg_hba.conf Certificate Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(hostssl|host)\s+.+\s+cert\s*$",
        },
        "check_func": "check_hba_cert",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "Certificate Auth",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "depends-on-cert-key"],
        },
        "replacement": "Ensure client certificates use PQC keys (ML-DSA or ECDSA P-384)",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "pg_hba_ldap",
        "name": "pg_hba.conf LDAP Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(host|local)\s+.+\s+ldap\s*$",
        },
        "check_func": "check_hba_ldap",
        "algorithm": {
            "algorithmFamily": "SASL",
            "algorithmName": "LDAP Auth",
            "primitive": "mac",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "depends-on-ldap-tls"],
        },
        "replacement": "Ensure LDAP connection uses TLS 1.3 with PQC ciphers",
        "priority": "P1-High",
        "effort": "Medium",
    },
    {
        "id": "pg_hba_gss",
        "name": "pg_hba.conf GSS/Kerberos Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(host|local)\s+.+\s+gss\s*$",
        },
        "check_func": "check_hba_gss",
        "algorithm": {
            "algorithmFamily": "SASL",
            "algorithmName": "GSS/Kerberos Auth",
            "primitive": "mac",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "depends-on-krb5-config"],
        },
        "replacement": "Ensure Kerberos uses AES-256, plan migration to PQC auth",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "pg_hba_ident",
        "name": "pg_hba.conf Ident Authentication",
        "category": "pg_auth",
        "file_patterns": ["pg_hba.conf"],
        "patterns": {
            "config": r"^\s*(host|local)\s+.+\s+ident\s*$",
        },
        "check_func": "check_hba_ident",
        "algorithm": {
            "algorithmFamily": "SASL",
            "algorithmName": "Ident Auth",
            "primitive": "mac",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["insecure-protocol", "deprecated", "no-crypto"],
        },
        "replacement": "Replace ident with scram-sha-256 in pg_hba.conf",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "pg_password_encryption",
        "name": "PostgreSQL password_encryption Setting",
        "category": "pg_auth",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*password_encryption\s*=\s*(md5|scram-sha-256)\s*$",
        },
        "check_func": "check_password_encryption",
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "Password Encryption",
            "primitive": "kdf",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["quantum-vulnerable", "hash-dependent"],
        },
        "replacement": "Set password_encryption = scram-sha-256",
        "priority": "P0-Critical",
        "effort": "Low",
    },
]
