"""PostgreSQL pgcrypto SQL function detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PGCRYPTO_SQL_RULES = [
    {
        "id": "pgp_sym_encrypt",
        "name": "pgp_sym_encrypt() - Symmetric Encryption",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bpgp_sym_encrypt\s*\(",
        },
        "check_func": "check_pgcrypto_sym",
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "pgcrypto Symmetric Encryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "symmetric", "pgcrypto"],
        },
        "replacement": "Ensure using AES-256 (default) - already quantum-safe",
        "priority": "P3-Low",
        "effort": "None",
    },
    {
        "id": "pgp_pub_encrypt",
        "name": "pgp_pub_encrypt() - Asymmetric Encryption (RSA)",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bpgp_pub_encrypt\s*\(",
        },
        "check_func": "check_pgcrypto_pub",
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "pgcrypto Asymmetric Encryption",
            "primitive": "key-encapsulation",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "pgcrypto-rsa"],
        },
        "replacement": "Migrate to pgp_sym_encrypt with ML-KEM key wrapping or use pgcrypto PQC extension",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pgp_pub_decrypt",
        "name": "pgp_pub_decrypt() - Asymmetric Decryption",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bpgp_pub_decrypt\s*\(",
        },
        "check_func": "check_pgcrypto_pub_decrypt",
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "pgcrypto Asymmetric Decryption",
            "primitive": "key-encapsulation",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "pgcrypto-rsa"],
        },
        "replacement": "Migrate to pgp_sym_decrypt with ML-KEM key unwrapping",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "pgp_sym_decrypt",
        "name": "pgp_sym_decrypt() - Symmetric Decryption",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bpgp_sym_decrypt\s*\(",
        },
        "check_func": "check_pgcrypto_sym_decrypt",
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "pgcrypto Symmetric Decryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "symmetric", "pgcrypto"],
        },
        "replacement": "None needed - already quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "pgp_sym_encrypt_bytea",
        "name": "pgp_sym_encrypt_bytea() - Bytea Symmetric Encryption",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bpgp_sym_encrypt_bytea\s*\(",
        },
        "check_func": "check_pgcrypto_sym_bytea",
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "pgcrypto Symmetric Bytea Encryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "symmetric", "pgcrypto"],
        },
        "replacement": "None needed - already quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "digest_md5",
        "name": "digest() with MD5",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bdigest\s*\([^,]+,\s*['\"]md5['\"]\s*\)",
        },
        "check_func": "check_digest_md5",
        "algorithm": {
            "algorithmFamily": "MD5",
            "algorithmName": "pgcrypto MD5 Digest",
            "primitive": "hash",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-vulnerable", "quantum-vulnerable", "pgcrypto"],
        },
        "replacement": "Replace digest(data, 'md5') with digest(data, 'sha256')",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "digest_sha1",
        "name": "digest() with SHA-1",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bdigest\s*\([^,]+,\s*['\"]sha1['\"]\s*\)",
        },
        "check_func": "check_digest_sha1",
        "algorithm": {
            "algorithmFamily": "SHA-1",
            "algorithmName": "pgcrypto SHA-1 Digest",
            "primitive": "hash",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-broken", "quantum-vulnerable", "pgcrypto"],
        },
        "replacement": "Replace digest(data, 'sha1') with digest(data, 'sha256')",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "digest_sha256",
        "name": "digest() with SHA-256",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bdigest\s*\([^,]+,\s*['\"]sha256['\"]\s*\)",
        },
        "check_func": "check_digest_sha256",
        "algorithm": {
            "algorithmFamily": "SHA-2",
            "algorithmName": "pgcrypto SHA-256 Digest",
            "primitive": "hash",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["collision-resistant", "quantum-weakened-but-safe", "pgcrypto"],
        },
        "replacement": "None needed - SHA-256 is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "hmac_sha256",
        "name": "hmac() with SHA-256",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bhmac\s*\([^,]+,\s*[^,]+,\s*['\"]sha256['\"]\s*\)",
        },
        "check_func": "check_hmac_sha256",
        "algorithm": {
            "algorithmFamily": "HMAC",
            "algorithmName": "pgcrypto HMAC-SHA256",
            "primitive": "mac",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-weakened-but-safe", "integrity-protected", "pgcrypto"],
        },
        "replacement": "None needed - HMAC-SHA256 is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "hmac_md5",
        "name": "hmac() with MD5",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bhmac\s*\([^,]+,\s*[^,]+,\s*['\"]md5['\"]\s*\)",
        },
        "check_func": "check_hmac_md5",
        "algorithm": {
            "algorithmFamily": "MD5",
            "algorithmName": "pgcrypto HMAC-MD5",
            "primitive": "mac",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-vulnerable", "quantum-vulnerable", "pgcrypto"],
        },
        "replacement": "Replace hmac(data, key, 'md5') with hmac(data, key, 'sha256')",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "gen_salt_bf",
        "name": "gen_salt() with Blowfish",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bgen_salt\s*\(\s*['\"]bf['\"]\s*\)",
        },
        "check_func": "check_gen_salt_bf",
        "algorithm": {
            "algorithmFamily": "Blowfish",
            "algorithmName": "pgcrypto Blowfish Salt",
            "primitive": "kdf",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 64,
            "securityProperties": ["small-block-size", "legacy", "pgcrypto"],
        },
        "replacement": "Replace gen_salt('bf') with gen_salt('xsha256') or use Argon2",
        "priority": "P1-High",
        "effort": "Medium",
    },
    {
        "id": "gen_salt_md5",
        "name": "gen_salt() with MD5",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bgen_salt\s*\(\s*['\"]md5['\"]\s*\)",
        },
        "check_func": "check_gen_salt_md5",
        "algorithm": {
            "algorithmFamily": "MD5",
            "algorithmName": "pgcrypto MD5 Salt",
            "primitive": "kdf",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-vulnerable", "quantum-vulnerable", "pgcrypto"],
        },
        "replacement": "Replace gen_salt('md5') with gen_salt('xsha256') or use Argon2",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "gen_salt_xsha256",
        "name": "gen_salt() with SHA-256",
        "category": "pgcrypto",
        "file_patterns": ["*.sql", "*.psql", "*.pgsql"],
        "patterns": {
            "sql": r"\bgen_salt\s*\(\s*['\"]xsha256['\"]\s*\)",
        },
        "check_func": "check_gen_salt_xsha256",
        "algorithm": {
            "algorithmFamily": "SHA-2",
            "algorithmName": "pgcrypto SHA-256 Salt",
            "primitive": "kdf",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-weakened-but-safe", "modern", "pgcrypto"],
        },
        "replacement": "None needed - xsha256 is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
]
