"""PostgreSQL SSL/TLS configuration detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PG_SSL_RULES = [
    {
        "id": "pg_ssl_enabled",
        "name": "PostgreSQL SSL Enabled",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf", "*.conf"],
        "patterns": {
            "config": r"^\s*ssl\s*=\s*(on|off|1|0)\s*$",
        },
        "check_func": "check_ssl_enabled",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL SSL",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["transport-encryption"],
        },
        "severity_when_off": "critical",
        "replacement": "Enable SSL: ssl = on",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "pg_ssl_min_protocol",
        "name": "PostgreSQL SSL Min Protocol Version",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_min_protocol_version\s*=\s*['\"]?([\w\d\.]+)['\"]?",
        },
        "check_func": "check_ssl_min_protocol",
        "vulnerable_values": ["TLSv1", "TLSv1.1", "TLSv1.2"],
        "safe_values": ["TLSv1.3"],
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL TLS Version",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "downgrade-risk"],
        },
        "replacement": "Set ssl_min_protocol_version = 'TLSv1.3'",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "pg_ssl_ciphers",
        "name": "PostgreSQL SSL Cipher Configuration",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_ciphers\s*=\s*['\"](.+?)['\"]",
        },
        "check_func": "check_ssl_ciphers",
        "vulnerable_ciphers": ["RC4", "DES", "3DES", "MD5", "NULL", "EXPORT", "aNULL", "eNULL"],
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL Cipher Suite",
            "primitive": "certificate",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["weak-cipher-risk"],
        },
        "replacement": "Use HIGH:!aNULL:!eNULL:!MD5:!RC4:!3DES:!DES",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "pg_ssl_cert_file",
        "name": "PostgreSQL SSL Certificate File",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_cert_file\s*=\s*['\"](.+?)['\"]",
        },
        "check_func": "check_ssl_cert_configured",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL SSL Certificate",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["certificate-configured"],
        },
        "replacement": "Ensure certificate uses PQC-compatible key (ML-KEM or ECDSA P-384)",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "pg_ssl_key_file",
        "name": "PostgreSQL SSL Key File",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_key_file\s*=\s*['\"](.+?)['\"]",
        },
        "check_func": "check_ssl_key_configured",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL SSL Key",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["key-configured"],
        },
        "replacement": "Ensure private key is RSA-4096+ or ECDSA P-384+ (quantum-resistant minimum)",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "pg_ssl_ca_file",
        "name": "PostgreSQL SSL CA File",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_ca_file\s*=\s*['\"](.+?)['\"]",
        },
        "check_func": "check_ssl_ca_configured",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL SSL CA",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["ca-configured"],
        },
        "replacement": "Ensure CA certificate uses SHA-256+ signing algorithm",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "pg_ssl_prefer_server_ciphers",
        "name": "PostgreSQL SSL Prefer Server Ciphers",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_prefer_server_ciphers\s*=\s*(on|off)\s*$",
        },
        "check_func": "check_ssl_prefer_server_ciphers",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL Cipher Preference",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["server-cipher-preference"],
        },
        "replacement": "Set ssl_prefer_server_ciphers = on",
        "priority": "P3-Low",
        "effort": "None",
    },
    {
        "id": "pg_ssl_ecdh_curve",
        "name": "PostgreSQL SSL ECDH Curve",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_ecdh_curve\s*=\s*['\"](.+?)['\"]",
        },
        "check_func": "check_ssl_ecdh_curve",
        "vulnerable_curves": ["P-256", "prime256v1", "secp256r1"],
        "safe_curves": ["X25519", "P-384", "P-521"],
        "algorithm": {
            "algorithmFamily": "ECDH",
            "algorithmName": "PostgreSQL ECDH Curve",
            "primitive": "key-exchange",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "shor-breakable"],
        },
        "replacement": "Use X25519 or P-384 curve (or ML-KEM hybrid)",
        "priority": "P1-High",
        "effort": "Medium",
    },
    {
        "id": "pg_ssl_dh_params",
        "name": "PostgreSQL SSL DH Parameters",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_dh_params_file\s*=\s*['\"](.+?)['\"]",
        },
        "check_func": "check_ssl_dh_params",
        "algorithm": {
            "algorithmFamily": "DH",
            "algorithmName": "PostgreSQL DH Parameters",
            "primitive": "key-exchange",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "logarithm-breakable"],
        },
        "replacement": "Remove DH params, use ECDH or ML-KEM instead",
        "priority": "P1-High",
        "effort": "Medium",
    },
    {
        "id": "pg_ssl_max_protocol",
        "name": "PostgreSQL SSL Max Protocol Version",
        "category": "pg_ssl",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*ssl_max_protocol_version\s*=\s*['\"]?([\w\d\.]+)['\"]?",
        },
        "check_func": "check_ssl_max_protocol",
        "algorithm": {
            "algorithmFamily": "TLS",
            "algorithmName": "PostgreSQL Max TLS Version",
            "primitive": "certificate",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["protocol-limit-configured"],
        },
        "replacement": "Ensure ssl_max_protocol_version allows TLSv1.3",
        "priority": "P3-Low",
        "effort": "None",
    },
]
