"""PostgreSQL WAL and backup encryption detection rules."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PG_WAL_BACKUP_RULES = [
    {
        "id": "pg_wal_level",
        "name": "PostgreSQL WAL Level",
        "category": "pg_wal",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*wal_level\s*=\s*(minimal|replica|logical)\s*$",
        },
        "check_func": "check_wal_level",
        "algorithm": {
            "algorithmFamily": "WAL",
            "algorithmName": "WAL Configuration",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["wal-configured"],
        },
        "replacement": "WAL itself is not encrypted - ensure filesystem encryption is enabled",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "pg_wal_encryption",
        "name": "PostgreSQL WAL Encryption (Enterprise)",
        "category": "pg_wal",
        "file_patterns": ["postgresql.conf", "postgresql.auto.conf"],
        "patterns": {
            "config": r"^\s*(wal_encryption|encryption)\s*=\s*(on|off|aes-256)\s*$",
        },
        "check_func": "check_wal_encryption",
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "WAL Encryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "wal-encrypted"],
        },
        "replacement": "None needed - AES-256 WAL encryption is quantum-safe",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "pg_dump_cipher",
        "name": "pg_dump Cipher Algorithm",
        "category": "pg_backup",
        "file_patterns": ["*.sh", "*.py", "*.sql", "*.conf"],
        "patterns": {
            "config": r"\bpg_dump\b.*--cipher-algorithm\s*(aes-?256-cbc| Blowfish|3des|aes-?128-cbc)",
            "python": r"\bpg_dump\b.*--cipher-algorithm\s*(aes-?256-cbc|Blowfish|3des|aes-?128-cbc)",
            "sql": r"\bpg_dump\b.*--cipher-algorithm\s*(aes-?256-cbc|Blowfish|3des|aes-?128-cbc)",
            "go": r"\bpg_dump\b.*--cipher-algorithm\s*(aes-?256-cbc|Blowfish|3des|aes-?128-cbc)",
            "c": r"\bpg_dump\b.*--cipher-algorithm\s*(aes-?256-cbc|Blowfish|3des|aes-?128-cbc)",
        },
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "pg_dump Backup Encryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "backup-encrypted"],
        },
        "replacement": "Ensure using --cipher-algorithm=aes-256-cbc for backups",
        "priority": "P3-Low",
        "effort": "Low",
    },
    {
        "id": "pg_dump_no_encrypt",
        "name": "pg_dump Without Encryption",
        "category": "pg_backup",
        "file_patterns": ["*.sh", "*.py", "*.sql", "*.conf"],
        "patterns": {
            "config": r"\bpg_dump\b(?!.*--cipher-algorithm)(?!.*--encrypt)(?!.*-C\s+\w+\.enc)",
            "python": r"\bpg_dump\b(?!.*--cipher-algorithm)(?!.*--encrypt)",
            "sql": r"\bpg_dump\b(?!.*--cipher-algorithm)(?!.*--encrypt)",
            "go": r"\bpg_dump\b(?!.*--cipher-algorithm)(?!.*--encrypt)",
            "c": r"\bpg_dump\b(?!.*--cipher-algorithm)(?!.*--encrypt)",
        },
        "algorithm": {
            "algorithmFamily": "WAL",
            "algorithmName": "Unencrypted Backup",
            "primitive": "encryption",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["no-backup-encryption", "data-exposure-risk"],
        },
        "replacement": "Add --cipher-algorithm=aes-256-cbc to pg_dump commands",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "pg_basebackup_encrypt",
        "name": "pg_basebackup Encryption",
        "category": "pg_backup",
        "file_patterns": ["*.sh", "*.py", "*.sql", "*.conf"],
        "patterns": {
            "config": r"\bpg_basebackup\b.*--encrypt\s*(on|off)",
            "python": r"\bpg_basebackup\b.*--encrypt\s*(on|off)",
            "sql": r"\bpg_basebackup\b.*--encrypt\s*(on|off)",
            "go": r"\bpg_basebackup\b.*--encrypt\s*(on|off)",
            "c": r"\bpg_basebackup\b.*--encrypt\s*(on|off)",
        },
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "pg_basebackup Encryption",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "backup-encrypted"],
        },
        "replacement": "Ensure using --encrypt=on for base backups",
        "priority": "P3-Low",
        "effort": "Low",
    },
    {
        "id": "pg_tablespace_encrypt",
        "name": "PostgreSQL Tablespace Encryption",
        "category": "pg_wal",
        "file_patterns": ["*.sql", "*.psql"],
        "patterns": {
            "sql": r"\b(CREATE\s+TABLESPACE|tablespace)\b",
        },
        "check_func": "check_tablespace_encrypt",
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "Tablespace Encryption",
            "primitive": "encryption",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["filesystem-encryption-dependent", "no-native-tde"],
        },
        "replacement": "Ensure tablespace filesystem uses LUKS/BitLocker encryption",
        "priority": "P1-High",
        "effort": "Medium",
    },
]
