"""Asymmetric crypto detection rules (RSA, ECDH, ECDSA, Ed25519, DSA, DH)."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

ASYMMETRIC_RULES = [
    {
        "id": "rsa1024",
        "name": "RSA-1024",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(RSA\.generate\(\s*1024|RSA\.import_key|PKCS1_v1_5\.new|PKCS1_OAEP\.new)",
            "java": r"\b(KeyPairGenerator\.getInstance\(['\"]RSA['\"]|RSA\.ECB)",
            "javascript": r"\b(crypto\.generateKeyPairSync\(['\"]rsa['\"]|createSign\(['\"]RSA-)",
            "go": r"\b(crypto/rsa|rsa\.GenerateKey|rsa\.DecryptPKCS1v15|rsa\.SignPKCS1v15)",
            "c": r"\b(RSA_generate_key_ex|RSA_public_encrypt|RSA_private_decrypt|RSA_sign|RSA_verify)",
            "config": r"\b(rsa[_\-]?1024)",
            "sql": r"\b(pgp_pub_encrypt|pgp_pub_decrypt|RSA-?1024)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "RSA-1024",
            "primitive": "key-encapsulation",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 80,
            "securityProperties": ["quantum-vulnerable", "classical-weak", "deprecated"],
        },
        "replacement": "ML-KEM-1024 (FIPS 203)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "rsa2048",
        "name": "RSA-2048",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(RSA\.generate\(\s*2048|from\s+Crypto\.PublicKey\s+import\s+RSA)",
            "java": r"\b(KeyPairGenerator\.getInstance\(['\"]RSA['\"])",
            "javascript": r"\b(crypto\.generateKeyPairSync\(['\"]rsa['\"],\s*\{.*bits:\s*2048)",
            "go": r"\b(rsa\.GenerateKey.*2048|rsa\.GenerateMultiPrimeKey.*2048)",
            "c": r"\b(RSA_generate_key_ex.*2048|pgcrypto_encrypt_pubkey)",
            "config": r"\b(rsa[_\-]?2048|RSA-2048)",
            "sql": r"\b(pgp_pub_encrypt|pgp_pub_decrypt)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "RSA-2048",
            "primitive": "key-encapsulation",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "shor-breakable"],
        },
        "replacement": "ML-KEM-1024 (FIPS 203)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "rsa4096",
        "name": "RSA-4096",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(RSA\.generate\(\s*4096)",
            "java": r"\b(KeyPairGenerator\.getInstance\(['\"]RSA['\"]).*4096",
            "javascript": r"\b(crypto\.generateKeyPairSync\(['\"]rsa['\"],\s*\{.*bits:\s*4096)",
            "go": r"\b(rsa\.GenerateKey.*4096)",
            "c": r"\b(RSA_generate_key_ex.*4096)",
            "config": r"\b(rsa[_\-]?4096|RSA-4096)",
            "sql": r"\b(RSA-?4096)",
        },
        "algorithm": {
            "algorithmFamily": "RSA",
            "algorithmName": "RSA-4096",
            "primitive": "key-encapsulation",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 140,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "extended-classical"],
        },
        "replacement": "ML-KEM-1024 (FIPS 203)",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "ecdh-p256",
        "name": "ECDH-secp256r1",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(ECDH\.new|ec\.SECP256R1|ec\.derive_private_key|EllipticCurve\.generate\(\s*ec\.SECP256R1)",
            "java": r"\b(KeyAgreement\.getInstance\(['\"]ECDH['\"]|ECGenParameterSpec\(['\"]secp256r1['\"])",
            "javascript": r"\b(crypto\.createECDH\(['\"]secp256r1['\"]|ECDH\(['\"]secp256r1['\"])",
            "go": r"\b(elliptic\.P256|crypto/ecdsa|ecdh\.P256)",
            "c": r"\b(P-256|secp256r1|NID_X9_62_prime256v1|SSL_CTX_set1_groups_list.*P-256)",
            "config": r"\b(secp256r1|prime256v1|P-256)",
            "sql": r"\b(ECDH|secp256r1|P-256)",
        },
        "algorithm": {
            "algorithmFamily": "ECDH",
            "algorithmName": "ECDH-secp256r1",
            "primitive": "key-exchange",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "shor-breakable"],
        },
        "replacement": "ML-KEM-768 + X25519 hybrid",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "ecdh-p384",
        "name": "ECDH-secp384r1",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(ec\.SECP384R1|EllipticCurve\.generate\(\s*ec\.SECP384R1)",
            "java": r"\b(ECGenParameterSpec\(['\"]secp384r1['\"])",
            "javascript": r"\b(crypto\.createECDH\(['\"]secp384r1['\"])",
            "go": r"\b(elliptic\.P384|ecdh\.P384)",
            "c": r"\b(P-384|secp384r1|NID_secp384r1)",
            "config": r"\b(secp384r1|P-384)",
            "sql": r"\b(ECDH.*384|secp384r1|P-384)",
        },
        "algorithm": {
            "algorithmFamily": "ECDH",
            "algorithmName": "ECDH-secp384r1",
            "primitive": "key-exchange",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 192,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "extended-classical"],
        },
        "replacement": "ML-KEM-1024 + X25519 hybrid",
        "priority": "P1-High",
        "effort": "High",
    },
    {
        "id": "ecdsa-p256",
        "name": "ECDSA-secp256r1",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(ec\.SECP256R1.*sign|ECDSA\(|from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+ec)",
            "java": r"\b(Signature\.getInstance\(['\"]SHA256withECDSA['\"])",
            "javascript": r"\b(createSign\(['\"]SHA256['\"]\).*ecdsa|sign\(['\"]sha256['\"]\).*ec)",
            "go": r"\b(ecdsa\.Sign\(|ecdsa\.Verify\(|crypto/ecdsa)",
            "c": r"\b(ECDSA_sign|ECDSA_verify|ECDSA_SIG)",
            "config": r"\b(ecdsa[_\-]?p?256|SHA256withECDSA)",
            "sql": r"\b(ECDSA|secp256r1.*sign)",
        },
        "algorithm": {
            "algorithmFamily": "ECDSA",
            "algorithmName": "ECDSA-secp256r1",
            "primitive": "digital-signature",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "signature-broken"],
        },
        "replacement": "ML-DSA-65 (FIPS 204)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "ed25519",
        "name": "Ed25519",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(ed25519\.Ed25519PrivateKey|from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+ed25519)",
            "java": r"\b(Signature\.getInstance\(['\"]Ed25519['\"])",
            "javascript": r"\b(crypto\.sign\(['\"]ed25519['\"]|generateKeyPairSync\(['\"]ed25519['\"])",
            "go": r"\b(ed25519\.GenerateKey|ed25519\.Sign|ed25519\.Verify|crypto/ed25519)",
            "c": r"\b(Ed25519)",
            "config": r"\b(ed25519|Ed25519)",
            "sql": r"\b(Ed25519|ed25519)",
        },
        "algorithm": {
            "algorithmFamily": "EdDSA",
            "algorithmName": "Ed25519",
            "primitive": "digital-signature",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "shor-breakable", "modern-but-pq-insecure"],
        },
        "replacement": "ML-DSA-65 (FIPS 204)",
        "priority": "P1-High",
        "effort": "Medium",
    },
    {
        "id": "dh2048",
        "name": "DH-2048",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(DH\.generate|from\s+Crypto\.PublicKey\s+import\s+DH|DiffieHellman)",
            "java": r"\b(KeyAgreement\.getInstance\(['\"]DH['\"]|DHParameterSpec)",
            "javascript": r"\b(crypto\.createDiffieHellman\(\s*2048|crypto\.createDiffieHellman\(\s*'\s*2048)",
            "go": r"\b(dh\.GenerateGroup|crypto/dh)",
            "c": r"\b(DH_generate_key|DH_compute_key)",
            "config": r"\b(diffie[-_]hellman|DH[_\-]?2048)",
            "sql": r"\b(DH-?2048|DiffieHellman)",
        },
        "algorithm": {
            "algorithmFamily": "DH",
            "algorithmName": "DH-2048",
            "primitive": "key-exchange",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "logarithm-breakable", "deprecated"],
        },
        "replacement": "ML-KEM-768 (FIPS 203)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "dsa",
        "name": "DSA",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(DSA\.generate|from\s+Crypto\.PublicKey\s+import\s+DSA)",
            "java": r"\b(Signature\.getInstance\(['\"]SHA256withDSA['\"])",
            "javascript": r"\b(generateKeyPairSync\(['\"]dsa['\"])",
            "go": r"\b(dsa\.GenerateKey|crypto/dsa)",
            "c": r"\b(DSA_generate_key|DSA_sign|DSA_verify)",
            "config": r"\b(DSA[_\-]?2048|dsa[_\-]?2048)",
            "sql": r"\b(DSA|dsa[_\-]?2048)",
        },
        "algorithm": {
            "algorithmFamily": "DSA",
            "algorithmName": "DSA",
            "primitive": "digital-signature",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "deprecated", "nist-deprecated"],
        },
        "replacement": "ML-DSA-65 (FIPS 204)",
        "priority": "P0-Critical",
        "effort": "High",
    },
    {
        "id": "x25519",
        "name": "X25519",
        "category": "asymmetric",
        "patterns": {
            "python": r"\b(X25519PrivateKey|from\s+cryptography\.hazmat\.primitives\.asymmetric\s+import\s+x25519)",
            "java": r"\b(KeyAgreement\.getInstance\(['\"]X25519['\"])",
            "javascript": r"\b(crypto\.X25519|generateKeyPairSync\(['\"]x25519['\"])",
            "go": r"\b(x25519\.KeyPair|crypto/x25519|ecdh\.X25519)",
            "c": r"\b(X25519|EVP_PKEY_X25519)",
            "config": r"\b(x25519|X25519)",
            "sql": r"\b(X25519|x25519)",
        },
        "algorithm": {
            "algorithmFamily": "ECDH",
            "algorithmName": "X25519",
            "primitive": "key-exchange",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-vulnerable", "modern-but-pq-insecure", "fast"],
        },
        "replacement": "ML-KEM-768 (FIPS 203)",
        "priority": "P1-High",
        "effort": "Medium",
    },
]
