"""Cipher detection rules (DES, 3DES, RC4, AES, ChaCha20, Blowfish)."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

CIPHER_RULES = [
    {
        "id": "des",
        "name": "DES/3DES",
        "category": "cipher",
        "patterns": {
            "python": r"\b(DES\.new|from\s+Crypto\.Cipher\s+import\s+DES|from\s+Crypto\.Cipher\s+import\s+DES3)",
            "java": r"\b(DES\.getInstance|DESede\.getInstance|Cipher\.getInstance\(['\"]DES/)",
            "javascript": r"\b(cipher\.createDecipheriv\(['\"]des-|createCipheriv\(['\"]des-)",
            "go": r"\b(crypto/des|des\.NewCipher|des\.NewTripleCipher)",
            "c": r"\b(DES_.*|EVP_des_|EVP_ede)",
            "config": r"\b(DES|des-cbc|des-ede)",
            "sql": r"\b(DES|'des'|\"des\")",
        },
        "algorithm": {
            "algorithmFamily": "DES",
            "algorithmName": "DES/3DES",
            "primitive": "encryption",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["key-size-broken", "quantum-vulnerable"],
        },
        "replacement": "AES-256-GCM",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "rc4",
        "name": "RC4",
        "category": "cipher",
        "patterns": {
            "python": r"\b(RC4\.new|from\s+Crypto\.Cipher\s+import\s+ARC4|ARC4\.new)",
            "java": r"\b(RC4\.getInstance|Cipher\.getInstance\(['\"]RC4)",
            "javascript": r"\b(createCipheriv\(['\"]rc4|createDecipheriv\(['\"]rc4)",
            "go": r"\b(rc4\.NewCipher|crypto/rc4)",
            "c": r"\b(EVP_rc4|RC4_set_key|RC4)",
            "config": r"\b(rc4|RC4)",
            "sql": r"\b(RC4|'rc4'|\"rc4\")",
        },
        "algorithm": {
            "algorithmFamily": "RC4",
            "algorithmName": "RC4",
            "primitive": "encryption",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["stream-cipher-broken", "bias-vulnerable", "quantum-vulnerable"],
        },
        "replacement": "AES-256-GCM / ChaCha20-Poly1305",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "blowfish",
        "name": "Blowfish",
        "category": "cipher",
        "patterns": {
            "python": r"\b(Blowfish\.new|from\s+Crypto\.Cipher\s+import\s+Blowfish)",
            "java": r"\b(Blowfish\.getInstance|Cipher\.getInstance\(['\"]Blowfish)",
            "javascript": r"\b(createCipheriv\(['\"]bf-|createDecipheriv\(['\"]bf-)",
            "go": r"\b(blowfish\.New|golang\.org/x/crypto/blowfish)",
            "c": r"\b(BF_.*|EVP_bf)",
            "config": r"\b(blowfish|Blowfish)",
            "sql": r"\b(gen_salt\(['\"]bf['\"]|'bf'|\"bf\")",
        },
        "algorithm": {
            "algorithmFamily": "Blowfish",
            "algorithmName": "Blowfish",
            "primitive": "encryption",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 64,
            "securityProperties": ["small-block-size", "legacy", "quantum-weak"],
        },
        "replacement": "AES-256-GCM",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "aes128",
        "name": "AES-128",
        "category": "cipher",
        "patterns": {
            "python": r"\b(AES\.new|from\s+Crypto\.Cipher\s+import\s+AES)",
            "java": r"\b(Cipher\.getInstance\(['\"]AES/|AES\.getInstance)",
            "javascript": r"\b(cipher\.createCipheriv\(['\"]aes-128|createDecipheriv\(['\"]aes-128)",
            "go": r"\b(aes\.NewCipher|crypto/aes)",
            "c": r"\b(EVP_aes_128|AES_.*128)",
            "config": r"\b(aes[-_]?128|AES[-_]?128)",
            "sql": r"\b(pgp_sym_encrypt\([^)]*['\"]aes128['\"]|'aes128'|\"aes128\")",
        },
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "AES-128",
            "primitive": "encryption",
            "risk": RISK_HIGH,
            "nistQuantumSecurityLevel": 2,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-weakened-but-safe", "grover-halves-key"],
        },
        "replacement": "AES-256-GCM",
        "priority": "P1-High",
        "effort": "Low",
    },
    {
        "id": "aes256",
        "name": "AES-256",
        "category": "cipher",
        "patterns": {
            "python": r"\b(AES\.new|from\s+Crypto\.Cipher\s+import\s+AES)",
            "java": r"\b(Cipher\.getInstance\(['\"]AES/)",
            "javascript": r"\b(cipher\.createCipheriv\(['\"]aes-256|createDecipheriv\(['\"]aes-256)",
            "go": r"\b(aes\.NewCipher)",
            "c": r"\b(EVP_aes_256|AES-256)",
            "config": r"\b(aes[-_]?256|AES[-_]?256)",
            "sql": r"\b(pgp_sym_encrypt\([^)]*['\"]aes256['\"]|'aes256'|\"aes256\")",
        },
        "algorithm": {
            "algorithmFamily": "AES",
            "algorithmName": "AES-256",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "grover-reduces-to-128"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "chacha20",
        "name": "ChaCha20-Poly1305",
        "category": "cipher",
        "patterns": {
            "python": r"\b(ChaCha20\.new|from\s+Crypto\.Cipher\s+import\s+ChaCha20|from\s+cryptography\.hazmat\.primitives\.ciphers\.algorithms\s+import\s+ChaCha20)",
            "java": r"\b(Cipher\.getInstance\(['\"]ChaCha20-Poly1305['\"])",
            "javascript": r"\b(cipher\.createCipheriv\(['\"]chacha20-poly1305['\"])",
            "go": r"\b(chacha20poly1305\.New|golang\.org/x/crypto/chacha20poly1305)",
            "c": r"\b(EVP_chacha20_poly1305)",
            "config": r"\b(chacha20[-_]?poly1305|ChaCha20)",
            "sql": r"\b(ChaCha20|'chacha20'|\"chacha20\")",
        },
        "algorithm": {
            "algorithmFamily": "ChaCha20",
            "algorithmName": "ChaCha20-Poly1305",
            "primitive": "encryption",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "authenticated", "modern"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
]
