"""Hash function detection rules (MD5, SHA-1, SHA-256, SHA-384, SHA-512, SHA3-256)."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

HASH_RULES = [
    {
        "id": "md5",
        "name": "MD5",
        "category": "hash",
        "patterns": {
            "python": r"\b(hashlib\.md5|MD5\.new|from\s+hashlib\s+import.*md5|digest\(['\"]md5['\"])",
            "java": r"\b(MessageDigest\.getInstance\(['\"]MD5['\"]|MD5\.getInstance)",
            "javascript": r"\b(crypto\.createHash\(['\"]md5['\"]|createHash\(['\"]md5['\"])",
            "go": r"\b(crypto/md5|md5\.New|md5\.Sum|crypto\.MD5)",
            "c": r"\b(MD5|EVP_get_digestbyname\(['\"]MD5['\"]|EVP_md5\(\))",
            "config": r"\b(md5|MD5)",
            "sql": r"\b(MD5\(|'md5'|\"md5\")",
        },
        "algorithm": {
            "algorithmFamily": "MD5",
            "algorithmName": "MD5",
            "primitive": "hash",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-vulnerable", "preimage-weak", "quantum-vulnerable"],
        },
        "replacement": "SHA-256 / SHA-3-256",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "sha1",
        "name": "SHA-1",
        "category": "hash",
        "patterns": {
            "python": r"\b(hashlib\.sha1|SHA\.new|from\s+hashlib\s+import.*sha1|digest\(['\"]sha1['\"])",
            "java": r"\b(MessageDigest\.getInstance\(['\"]SHA-?1['\"])",
            "javascript": r"\b(crypto\.createHash\(['\"]sha1['\"])",
            "go": r"\b(crypto/sha1|sha1\.New|sha1\.Sum|crypto\.SHA1)",
            "c": r"\b(SHA1|EVP_sha1\(\)|EVP_get_digestbyname\(['\"]sha1['\"])\)",
            "config": r"\b(sha1|SHA-?1)",
            "sql": r"\b(SHA1\(|'sha1'|\"sha1\")",
        },
        "algorithm": {
            "algorithmFamily": "SHA-1",
            "algorithmName": "SHA-1",
            "primitive": "hash",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 0,
            "securityProperties": ["collision-broken", "quantum-vulnerable"],
        },
        "replacement": "SHA-256 / SHA-3-256",
        "priority": "P0-Critical",
        "effort": "Low",
    },
    {
        "id": "sha256",
        "name": "SHA-256",
        "category": "hash",
        "patterns": {
            "python": r"\b(hashlib\.sha256|from\s+hashlib\s+import.*sha256)",
            "java": r"\b(MessageDigest\.getInstance\(['\"]SHA-?256['\"])",
            "javascript": r"\b(crypto\.createHash\(['\"]sha256['\"])",
            "go": r"\b(crypto/sha256|sha256\.New|sha256\.Sum256)",
            "c": r"\b(SHA256|EVP_sha256\(\)|SHA256_DIGEST_LENGTH|EVP_get_digestbyname\(['\"]sha256['\"])\)",
            "config": r"\b(sha[-_]?256|SHA[-_]?256)",
            "sql": r"\b(digest\([^,]+,\s*['\"]sha256['\"]|'sha256'|\"sha256\")",
        },
        "algorithm": {
            "algorithmFamily": "SHA-2",
            "algorithmName": "SHA-256",
            "primitive": "hash",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["collision-resistant", "quantum-weakened-but-safe"],
        },
        "replacement": "None needed",
        "priority": "P3-Low",
        "effort": "None",
    },
    {
        "id": "sha384",
        "name": "SHA-384",
        "category": "hash",
        "patterns": {
            "python": r"\b(hashlib\.sha384|from\s+hashlib\s+import.*sha384)",
            "java": r"\b(MessageDigest\.getInstance\(['\"]SHA-?384['\"])",
            "javascript": r"\b(crypto\.createHash\(['\"]sha384['\"])",
            "go": r"\b(crypto/sha512.*sha384|sha512\.Sum384)",
            "c": r"\b(SHA384|EVP_sha384\(\))",
            "config": r"\b(sha[-_]?384|SHA[-_]?384)",
            "sql": r"\b(SHA384|'sha384'|\"sha384\")",
        },
        "algorithm": {
            "algorithmFamily": "SHA-2",
            "algorithmName": "SHA-384",
            "primitive": "hash",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 384,
            "securityProperties": ["collision-resistant", "quantum-safe"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "sha512",
        "name": "SHA-512",
        "category": "hash",
        "patterns": {
            "python": r"\b(hashlib\.sha512|from\s+hashlib\s+import.*sha512)",
            "java": r"\b(MessageDigest\.getInstance\(['\"]SHA-?512['\"])",
            "javascript": r"\b(crypto\.createHash\(['\"]sha512['\"])",
            "go": r"\b(crypto/sha512|sha512\.New|sha512\.Sum512)",
            "c": r"\b(SHA512|EVP_sha512\(\))",
            "config": r"\b(sha[-_]?512|SHA[-_]?512)",
            "sql": r"\b(SHA512|'sha512'|\"sha512\")",
        },
        "algorithm": {
            "algorithmFamily": "SHA-2",
            "algorithmName": "SHA-512",
            "primitive": "hash",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 512,
            "securityProperties": ["collision-resistant", "quantum-safe"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "sha3_256",
        "name": "SHA3-256",
        "category": "hash",
        "patterns": {
            "python": r"\b(hashlib\.sha3_256|from\s+hashlib\s+import.*sha3_256)",
            "java": r"\b(MessageDigest\.getInstance\(['\"]SHA3-?256['\"])",
            "javascript": r"\b(crypto\.createHash\(['\"]sha3-256['\"])",
            "go": r"\b(golang\.org/x/crypto/sha3|sha3\.New256)",
            "c": r"\b(EVP_sha3_256)",
            "config": r"\b(sha3[-_]?256|SHA3[-_]?256)",
            "sql": r"\b(digest\([^,]+,\s*['\"]sha3-256['\"]|'sha3-256'|\"sha3-256\")",
        },
        "algorithm": {
            "algorithmFamily": "SHA-3",
            "algorithmName": "SHA3-256",
            "primitive": "hash",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["collision-resistant", "quantum-safe", "nist-standardized"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
]
