"""KDF detection rules (PBKDF2, HKDF, bcrypt, Argon2, scrypt)."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

KDF_RULES = [
    {
        "id": "pbkdf2",
        "name": "PBKDF2",
        "category": "kdf",
        "patterns": {
            "python": r"\b(PBKDF2|from\s+Crypto\.Protocol\.KDF\s+import\s+PBKDF2|from\s+cryptography\.hazmat\.primitives\.kdf\.pbkdf2)",
            "java": r"\b(SecretKeyFactory\.getInstance\(['\"]PBKDF2)",
            "javascript": r"\b(crypto\.pbkdf2|crypto\.pbkdf2Sync)",
            "go": r"\b(pbkdf2\.Key|golang\.org/x/crypto/pbkdf2)",
            "c": r"\b(PKCS5_PBKDF2_HMAC)",
            "config": r"\b(pbkdf2|PBKDF2)",
            "sql": r"\b(pbkdf2|PBKDF2)",
        },
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "PBKDF2",
            "primitive": "kdf",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-weakened-but-safe", "iteration-dependent"],
        },
        "replacement": "Consider migrating to Argon2id",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "hkdf",
        "name": "HKDF",
        "category": "kdf",
        "patterns": {
            "python": r"\b(HKDF|from\s+cryptography\.hazmat\.primitives\.kdf\.hkdf)",
            "java": r"\b(HKDF\.getInstance|HKDFParameterSpec)",
            "javascript": r"\b(crypto\.hkdf|crypto\.HKDF)",
            "go": r"\b(hkdf\.New|golang\.org/x/crypto/hkdf)",
            "c": r"\b(EVP_PKEY_CTX_new_id\(['\"]EVP_PKEY_HKDF['\"]\))",
            "config": r"\b(hkdf|HKDF)",
            "sql": r"\b(hkdf|HKDF)",
        },
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "HKDF",
            "primitive": "kdf",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-weakened-but-safe", "modern"],
        },
        "replacement": "None needed",
        "priority": "P3-Low",
        "effort": "None",
    },
    {
        "id": "bcrypt",
        "name": "bcrypt",
        "category": "kdf",
        "patterns": {
            "python": r"\b(bcrypt\.hashpw|from\s+bcrypt\s+import|bcrypt\.gensalt)",
            "java": r"\b(BCrypt\.hashpw|BCrypt\.checkpw)",
            "javascript": r"\b(bcrypt\.hash|bcrypt\.compare|bcryptjs)",
            "go": r"\b(bcrypt\.GenerateFromPassword|golang\.org/x/crypto/bcrypt)",
            "c": r"\b(bcrypt)",
            "config": r"\b(bcrypt|BCrypt)",
            "sql": r"\b(gen_salt\(['\"]bf['\"])",
        },
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "bcrypt",
            "primitive": "kdf",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-weakened-but-safe", "memory-hard"],
        },
        "replacement": "Consider migrating to Argon2id",
        "priority": "P2-Medium",
        "effort": "Medium",
    },
    {
        "id": "argon2",
        "name": "Argon2",
        "category": "kdf",
        "patterns": {
            "python": r"\b(argon2\.hash_password|from\s+argon2\s+import|argon2\.PasswordHasher)",
            "java": r"\b(Argon2Factory\.create|Argon2\.getInstance)",
            "javascript": r"\b(argon2\.hash|argon2\.verify)",
            "go": r"\b(argon2\.IDKey|argon2\.Key|golang\.org/x/crypto/argon2)",
            "c": r"\b(argon2)",
            "config": r"\b(argon2|Argon2)",
            "sql": r"\b(argon2|Argon2)",
        },
        "algorithm": {
            "algorithmFamily": "KDF",
            "algorithmName": "Argon2",
            "primitive": "kdf",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-safe", "memory-hard", "nist-recommended"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
]
