"""MAC detection rules (HMAC, SCRAM)."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

MAC_RULES = [
    {
        "id": "hmac_sha256",
        "name": "HMAC-SHA256",
        "category": "mac",
        "patterns": {
            "python": r"\b(hmac\.new.*sha256|HMAC\.new|from\s+hmac\s+import)",
            "java": r"\b(Mac\.getInstance\(['\"]HmacSHA256['\"])",
            "javascript": r"\b(crypto\.createHmac\(['\"]sha256['\"])",
            "go": r"\b(hmac\.New.*sha256|crypto/hmac)",
            "c": r"\b(HMAC\(.*EVP_sha256)",
            "config": r"\b(HMAC[-_]SHA256|hmac[-_]sha256)",
            "sql": r"\b(hmac\([^,]+,\s*[^,]+,\s*['\"]sha256['\"])",
        },
        "algorithm": {
            "algorithmFamily": "HMAC",
            "algorithmName": "HMAC-SHA256",
            "primitive": "mac",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-weakened-but-safe", "integrity-protected"],
        },
        "replacement": "None needed",
        "priority": "P3-Low",
        "effort": "None",
    },
    {
        "id": "scram_sha256",
        "name": "SCRAM-SHA-256",
        "category": "mac",
        "patterns": {
            "python": r"\b(scram[-_]?sha[-_]?256|SCRAM)",
            "java": r"\b(scram[-_]?sha[-_]?256|SCRAM)",
            "javascript": r"\b(scram[-_]?sha[-_]?256|SCRAM)",
            "go": r"\b(scram[-_]?sha[-_]?256|SCRAM)",
            "c": r"\b(SCRAM|scram_sha256)",
            "config": r"\b(scram[-_]?sha[-_]?256|SCRAM-SHA-256)",
            "sql": r"\b(scram[-_]?sha[-_]?256|SCRAM-SHA-256)",
        },
        "algorithm": {
            "algorithmFamily": "SASL",
            "algorithmName": "SCRAM-SHA-256",
            "primitive": "mac",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-weakened-but-safe", "salted", "modern-auth"],
        },
        "replacement": "None needed",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "jwt_hs256",
        "name": "JWT HS256",
        "category": "mac",
        "patterns": {
            "python": r"\b(jwt\.encode.*HS256|PyJWT|jsonwebtoken)",
            "java": r"\b(Jwts\.builder\(\)\.signWith.*HS256|io\.jsonwebtoken)",
            "javascript": r"\b(jsonwebtoken\.sign|jwt\.sign\(['\"].*['\"].*\{.*algorithm:\s*['\"]HS256)",
            "go": r"\b(jwt\.SignedString|jwt\.SigningMethodHS256)",
            "c": r"\b(HS256)",
            "config": r"\b(HS256|HMAC-SHA256.*JWT)",
            "sql": r"\b(HS256|JWT.*HS256)",
        },
        "algorithm": {
            "algorithmFamily": "JWT",
            "algorithmName": "JWT HS256",
            "primitive": "mac",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 128,
            "securityProperties": ["quantum-weakened-but-safe", "symmetric-jwt"],
        },
        "replacement": "None needed",
        "priority": "P3-Low",
        "effort": "None",
    },
    {
        "id": "jwt_rs256",
        "name": "JWT RS256",
        "category": "mac",
        "patterns": {
            "python": r"\b(jwt\.encode.*RS256|PyJWT.*RSA)",
            "java": r"\b(Jwts\.builder\(\)\.signWith.*RS256|SHA256withRSA)",
            "javascript": r"\b(jsonwebtoken\.sign.*RS256|jwt\.sign\(['\"].*['\"].*\{.*algorithm:\s*['\"]RS256)",
            "go": r"\b(jwt\.SignedString.*RS256|jwt\.SigningMethodRS256)",
            "c": r"\b(RS256)",
            "config": r"\b(RS256|RSA-SHA256.*JWT)",
            "sql": r"\b(RS256|JWT.*RS256)",
        },
        "algorithm": {
            "algorithmFamily": "JWT",
            "algorithmName": "JWT RS256",
            "primitive": "digital-signature",
            "risk": RISK_CRITICAL,
            "nistQuantumSecurityLevel": 0,
            "classicalSecurityLevel": 112,
            "securityProperties": ["quantum-vulnerable", "rsa-signature"],
        },
        "replacement": "JWT with ML-DSA-65 (FIPS 204)",
        "priority": "P0-Critical",
        "effort": "High",
    },
]
