"""Post-quantum cryptography detection rules (ML-KEM, ML-DSA, Falcon, SPHINCS+)."""

RISK_CRITICAL = 0
RISK_HIGH = 1
RISK_SAFE = 2

PQC_RULES = [
    {
        "id": "ml_kem",
        "name": "ML-KEM (Kyber)",
        "category": "pqc",
        "patterns": {
            "python": r"\b(ml_kem|MLKEM|kyber|Kyber|from\s+oqs\s+import\s+kem|liboqs)",
            "java": r"\b(ML-KEM|Kyber|BouncyCastle.*MLKEM)",
            "javascript": r"\b(ml-kem|MLKEM|kyber|Kyber)",
            "go": r"\b(mlkem|ML-KEM|ml_kem|circl.*mlkem)",
            "c": r"\b(ML[-_]?KEM|Kyber|OQS_KEM)",
            "config": r"\b(ml[-_]?kem|ML-KEM|kyber|Kyber)",
            "sql": r"\b(ML[-_]?KEM|Kyber)",
        },
        "algorithm": {
            "algorithmFamily": "ML-KEM",
            "algorithmName": "ML-KEM (Kyber)",
            "primitive": "key-exchange",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "nist-standardized", "fips-203"],
        },
        "replacement": "None needed - already PQC",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "ml_dsa",
        "name": "ML-DSA (Dilithium)",
        "category": "pqc",
        "patterns": {
            "python": r"\b(ml_dsa|MLDSA|dilithium|Dilithium|from\s+oqs\s+import\s+sign)",
            "java": r"\b(ML-DSA|Dilithium|BouncyCastle.*MLDSA)",
            "javascript": r"\b(ml-dsa|MLDSA|dilithium|Dilithium)",
            "go": r"\b(mldsa|ML-DSA|ml_dsa|circl.*mldsa)",
            "c": r"\b(ML[-_]?DSA|Dilithium|OQS_SIG)",
            "config": r"\b(ml[-_]?dilithium|ML-DSA|dilithium|Dilithium)",
            "sql": r"\b(ML[-_]?DSA|Dilithium)",
        },
        "algorithm": {
            "algorithmFamily": "ML-DSA",
            "algorithmName": "ML-DSA (Dilithium)",
            "primitive": "digital-signature",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "nist-standardized", "fips-204"],
        },
        "replacement": "None needed - already PQC",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "falcon",
        "name": "Falcon",
        "category": "pqc",
        "patterns": {
            "python": r"\b(falcon|Falcon|from\s+oqs\s+import\s+sign.*falcon)",
            "java": r"\b(Falcon)",
            "javascript": r"\b(falcon|Falcon)",
            "go": r"\b(falcon|Falcon)",
            "c": r"\b(Falcon|NTRU)",
            "config": r"\b(falcon|Falcon)",
            "sql": r"\b(Falcon|falcon)",
        },
        "algorithm": {
            "algorithmFamily": "Falcon",
            "algorithmName": "Falcon",
            "primitive": "digital-signature",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "compact-signatures", "nist-standardized"],
        },
        "replacement": "None needed - already PQC",
        "priority": "P4-Safe",
        "effort": "None",
    },
    {
        "id": "sphincs_plus",
        "name": "SPHINCS+",
        "category": "pqc",
        "patterns": {
            "python": r"\b(sphincs|SPHINCS|from\s+oqs\s+import\s+sign.*sphincs)",
            "java": r"\b(SPHINCS|SPHINCSPlus)",
            "javascript": r"\b(sphincs|SPHINCS)",
            "go": r"\b(sphincs|SPHINCS)",
            "c": r"\b(SPHINCS|SLH-DSA)",
            "config": r"\b(sphincs|SPHINCS|slh[-_]?dsa|SLH-DSA)",
            "sql": r"\b(SPHINCS|SLH-DSA)",
        },
        "algorithm": {
            "algorithmFamily": "SLH-DSA",
            "algorithmName": "SPHINCS+ (SLH-DSA)",
            "primitive": "digital-signature",
            "risk": RISK_SAFE,
            "nistQuantumSecurityLevel": 1,
            "classicalSecurityLevel": 256,
            "securityProperties": ["quantum-resistant", "hash-based", "nist-standardized", "conservative"],
        },
        "replacement": "None needed - already PQC",
        "priority": "P4-Safe",
        "effort": "None",
    },
]
